version: '3.8'
services:

  API:
    image: '3c6bfe542a29'
    ports:
      - "8085:3333"
    depends_on:
      PostgreSQL:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://PostgreSQL:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=123456
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    networks:
      - n1
    

  PostgreSQL:
    image: postgres
    restart: always
    volumes:
      - pgdata1:/var/lib/postgresql/data/
   
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=123456
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    networks:
      - n1
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5


volumes:
  pgdata1:
    external: true
         

networks:
  n1:
    driver: bridge
